### ISSUE TITLE
TODO before release

### ISSUE THREAD

**Issue by vvo** [algolia/talksearch#4]
- [x] Update issue template
- [x] Update GitHub desc with messaging
- [x] Update html page desc with messaging
- [x] Ensure README is good enough to: explain the project, allow contributions
- [x] Reference this repository from talksearch-embed (a single repository should explain what is talksearch briefly, website then handles it)
- [x] Make project public (along with talksearch-embed being public)

WDYT? Anything else? Add it.

**Comment by Haroenv** [comment]
All done
